- name: delete '{{tomcat.dir}}/webapps/{{war.context}}'
  file:
    path: '$HOME/{{tomcat.dir}}/webapps/{{war.context}}'
    state: absent
- name: download the war file
  get_url:
    url: "{{artifactory.repo}}/{{war.path}}/{{war.name}}/{{app_version}}/{{war.name}}-{{app_version}}.war"
    dest: "$HOME/installers/{{war.name}}-{{app_version}}.war"
    force: true
    timeout: 5
    validate_certs: no
- name: create '{{tomcat.dir}}/webapps/{{war.context}}/'
  file:
    path: '$HOME/{{tomcat.dir}}/webapps/{{war.context}}'
    state: directory
    mode: 0755
- name: extract '{{war.context}}.war'
  unarchive:
    remote_src: yes
    src: "$HOME/installers/{{war.name}}-{{app_version}}.war"
    dest: '$HOME/{{tomcat.dir}}/webapps/{{war.context}}'
- name: Generate the config files
  template:
    src: application.properties.j2
    dest: '$HOME/{{tomcat.dir}}/webapps/{{war.context}}/WEB-INF/classes/application.properties'
